---
- name: Update all packages to their latest version
  hosts: all
  serial: 1
  become: true

  tasks:

    - name: Update all packages to their latest version
      ansible.builtin.apt:
        name: "*"
        state: latest
        update_cache: true
